services:
  redis:
    container_name: aqt-redis
    image: 'redis:latest'
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - traefik-public

  traeifk:
    image: traefik:3.3
    container_name: aqt-traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${APP_PORT}:80"
    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --accesslog
      - --log
      - --log.level=DEBUG
      - --api
      - --api.insecure=true
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
    networks:
      - traefik-public

  backend:
    image: "registry.craazzzyyfoxx.me/aqt-backend:latest"
    container_name: aqt-backend
    build:
      context: ./backend
      args:
        APP_PATH: app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --loop uvloop
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - PROJECT_URL=${PROJECT_URL}
      - REDIS_URL=${REDIS_URL}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    develop:
      watch:
        - path: ./backend/app
          action: sync
          target: /src
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.backend-http.rule=PathPrefix(`/api`)
      - traefik.http.routers.backend-http.entrypoints=http
      - traefik.http.services.backend-http.loadbalancer.server.port=8000
    volumes:
      - ./logs/backend:/logs
      - ./backend/htmlcov:/app/htmlcov
    networks:
      - traefik-public

  parser:
    image: registry.craazzzyyfoxx.me/aqt-parser:latest
    container_name: aqt-parser
    build:
      context: ./backend
      args:
        APP_PATH: parser
    command: uvicorn main:app --host 0.0.0.0 --port 8081 --loop uvloop
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - PROJECT_URL=${PROJECT_URL}
      - REDIS_URL=${REDIS_URL}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - CHALLONGE_API_KEY=${CHALLONGE_API_KEY}
      - CHALLONGE_USERNAME=${CHALLONGE_USERNAME}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.parser-api-http.rule=PathPrefix(`/parser`)
      - traefik.http.routers.parser-api-http.entrypoints=http
      - traefik.http.services.parser-api-http.loadbalancer.server.port=8081
    develop:
      watch:
        - path: ./backend/parser
          action: sync
          target: /src
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
    depends_on:
      - redis
    volumes:
      - ./logs/parser:/logs
    networks:
      - traefik-public

  frontend:
    image: registry.craazzzyyfoxx.me/frontend:latest
    container_name: aqt-frontend
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    environment:
      - NEXT_API_URL=${NEXT_API_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_CACHE_POLICY=${NEXT_PUBLIC_CACHE_POLICY}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.frontend-http.rule=PathPrefix(`/`)
      - traefik.http.routers.frontend-http.entrypoints=http
      - traefik.http.services.frontend-http.loadbalancer.server.port=3000
    volumes:
      - ./logs/frontend:/logs
    networks:
      - traefik-public

volumes:
  redis-data:

networks:
  traefik-public:
    external: false
