"""empty message

Revision ID: 0b45b61f373b
Revises: 41e1e97d7350
Create Date: 2024-10-13 00:26:57.942717

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b45b61f373b"
down_revision: str | None = "41e1e97d7350"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tournament",
        sa.Column("is_finished", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tournament", "is_finished")
    # ### end Alembic commands ###
