"""empty message

Revision ID: 1075af26d847
Revises: feb6e1024730
Create Date: 2025-03-01 13:32:31.111324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1075af26d847"
down_revision: Union[str, None] = "feb6e1024730"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_algorithms",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analytics_shifts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tournament_id", sa.BigInteger(), nullable=False),
        sa.Column("algorithm_id", sa.BigInteger(), nullable=False),
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column("shift_one", sa.Integer(), nullable=True),
        sa.Column("shift_two", sa.Integer(), nullable=True),
        sa.Column("calculated_shift", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["algorithm_id"], ["analytics_algorithms.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["player_id"], ["player.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tournament_id"], ["tournament.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analytics_tournament",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tournament_id", sa.BigInteger(), nullable=False),
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("shift", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["player_id"], ["player.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tournament_id"], ["tournament.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("analytics_predictions", "algorithm")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analytics_predictions",
        sa.Column(
            "algorithm",
            sa.VARCHAR(),
            server_default=sa.text("'points'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("analytics_tournament")
    op.drop_table("analytics_shifts")
    op.drop_table("analytics_algorithms")
    # ### end Alembic commands ###
