"""empty message

Revision ID: 1212b91f0782
Revises: 8dadcd2ae8b0
Create Date: 2024-10-18 14:07:07.986056

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1212b91f0782"
down_revision: str | None = "8dadcd2ae8b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_challonge_team_id", table_name="challonge_team")
    op.drop_index("ix_encounter_id", table_name="encounter")
    op.drop_index("ix_gamemode_id", table_name="gamemode")
    op.drop_index("ix_hero_id", table_name="hero")
    op.drop_index("ix_map_id", table_name="map")
    op.drop_index("ix_match_id", table_name="match")
    op.drop_index("ix_match_statistics_id", table_name="match_statistics")
    op.drop_index("ix_player_id", table_name="player")
    op.drop_index("ix_standing_id", table_name="standing")
    op.drop_index("ix_team_id", table_name="team")
    op.drop_index("ix_tournament_id", table_name="tournament")
    op.drop_index("ix_tournament_group_id", table_name="tournament_group")
    op.drop_index("ix_user_id", table_name="user")
    op.drop_index("ix_user_battle_tag_id", table_name="user_battle_tag")
    op.drop_index("ix_user_discord_id", table_name="user_discord")
    op.drop_index("ix_user_twitch_id", table_name="user_twitch")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_user_twitch_id", "user_twitch", ["id"], unique=False)
    op.create_index("ix_user_discord_id", "user_discord", ["id"], unique=False)
    op.create_index("ix_user_battle_tag_id", "user_battle_tag", ["id"], unique=False)
    op.create_index("ix_user_id", "user", ["id"], unique=False)
    op.create_index("ix_tournament_group_id", "tournament_group", ["id"], unique=False)
    op.create_index("ix_tournament_id", "tournament", ["id"], unique=False)
    op.create_index("ix_team_id", "team", ["id"], unique=False)
    op.create_index("ix_standing_id", "standing", ["id"], unique=False)
    op.create_index("ix_player_id", "player", ["id"], unique=False)
    op.create_index("ix_match_statistics_id", "match_statistics", ["id"], unique=False)
    op.create_index("ix_match_id", "match", ["id"], unique=False)
    op.create_index("ix_map_id", "map", ["id"], unique=False)
    op.create_index("ix_hero_id", "hero", ["id"], unique=False)
    op.create_index("ix_gamemode_id", "gamemode", ["id"], unique=False)
    op.create_index("ix_encounter_id", "encounter", ["id"], unique=False)
    op.create_index("ix_challonge_team_id", "challonge_team", ["id"], unique=False)
    # ### end Alembic commands ###
