"""empty message

Revision ID: 41e1e97d7350
Revises: e7d5680203b8
Create Date: 2024-10-13 00:05:14.496589

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41e1e97d7350"
down_revision: str | None = "e7d5680203b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tournament_number_is_league_key", "tournament", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "tournament_number_is_league_key", "tournament", ["number", "is_league"]
    )
    # ### end Alembic commands ###
