"""empty message

Revision ID: 532d0ac72498
Revises: a0eb19c3b7ee
Create Date: 2024-10-16 12:57:10.515903

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "532d0ac72498"
down_revision: str | None = "a0eb19c3b7ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tournament", sa.Column("start_date", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "tournament", sa.Column("end_date", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tournament", "end_date")
    op.drop_column("tournament", "start_date")
    # ### end Alembic commands ###
