"""empty message

Revision ID: 57ce862080c0
Revises: dcca4c75f32e
Create Date: 2024-08-20 19:09:32.599096

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57ce862080c0"
down_revision: str | None = "dcca4c75f32e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("encounter", sa.Column("closeness", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("encounter", "closeness")
    # ### end Alembic commands ###
