"""empty message

Revision ID: 58990db419cf
Revises: e4015fc886cc
Create Date: 2024-10-12 23:51:50.479147

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58990db419cf"
down_revision: str | None = "e4015fc886cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tournament",
        sa.Column("is_league", sa.Boolean(), server_default="false", nullable=False),
    )
    op.drop_constraint("tournament_number_key", "tournament", type_="unique")
    op.create_unique_constraint(None, "tournament", ["number", "is_league"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tournament", type_="unique")
    op.create_unique_constraint("tournament_number_key", "tournament", ["number"])
    op.drop_column("tournament", "is_league")
    # ### end Alembic commands ###
