"""empty message

Revision ID: 70cc654fb60b
Revises: 0470f653c567
Create Date: 2024-08-22 03:58:15.136874

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70cc654fb60b"
down_revision: str | None = "0470f653c567"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hero",
        sa.Column("color", sa.String(), server_default="#ffffff", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hero", "color")
    # ### end Alembic commands ###
