"""empty message

Revision ID: 71a9fe8a10c5
Revises: 78d75ad7143c
Create Date: 2025-02-24 01:36:38.089087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a9fe8a10c5'
down_revision: Union[str, None] = '78d75ad7143c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('algorithm', sa.String(), server_default='points', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics', 'algorithm')
    # ### end Alembic commands ###
