"""empty message

Revision ID: 8dadcd2ae8b0
Revises: 8e5740828039
Create Date: 2024-10-17 14:56:40.576135

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8dadcd2ae8b0"
down_revision: str | None = "8e5740828039"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("standing", sa.Column("tb", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("standing", "tb")
    # ### end Alembic commands ###
