"""empty message

Revision ID: 8e85bcd266b0
Revises: 8fc92da0b204
Create Date: 2024-10-20 15:15:08.836023

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e85bcd266b0"
down_revision: str | None = "8fc92da0b204"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_match_statistics_hero_id"),
        "match_statistics",
        ["hero_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_statistics_match_id"),
        "match_statistics",
        ["match_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_statistics_round"), "match_statistics", ["round"], unique=False
    )
    op.create_index(
        op.f("ix_match_statistics_team_id"),
        "match_statistics",
        ["team_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_statistics_user_id"),
        "match_statistics",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_match_statistics_user_id"), table_name="match_statistics")
    op.drop_index(op.f("ix_match_statistics_team_id"), table_name="match_statistics")
    op.drop_index(op.f("ix_match_statistics_round"), table_name="match_statistics")
    op.drop_index(op.f("ix_match_statistics_match_id"), table_name="match_statistics")
    op.drop_index(op.f("ix_match_statistics_hero_id"), table_name="match_statistics")
    # ### end Alembic commands ###
