"""empty message

Revision ID: a39cf19146e9
Revises: 2e53410d9154
Create Date: 2025-01-08 00:09:20.361598

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = "a39cf19146e9"
down_revision: str | None = "2e53410d9154"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    encounterstatus = ENUM(
        "COMPLETED", "PENDING", "OPEN", name="encounterstatus", create_type=True
    )
    encounterstatus.create(op.get_bind())
    op.add_column(
        "encounter",
        sa.Column(
            "status",
            sa.Enum("COMPLETED", "PENDING", "OPEN", name="encounterstatus"),
            nullable=False,
        ),
    )
    op.alter_column(
        "encounter", "home_team_id", existing_type=sa.BIGINT(), nullable=True
    )
    op.alter_column(
        "encounter", "away_team_id", existing_type=sa.BIGINT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "encounter", "away_team_id", existing_type=sa.BIGINT(), nullable=False
    )
    op.alter_column(
        "encounter", "home_team_id", existing_type=sa.BIGINT(), nullable=False
    )
    op.drop_column("encounter", "status")
    # ### end Alembic commands ###
