"""empty message

Revision ID: beb33d17062a
Revises: 58990db419cf
Create Date: 2024-10-12 23:52:30.434155

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "beb33d17062a"
down_revision: str | None = "58990db419cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
