"""empty message

Revision ID: dcc41cd48cc1
Revises: df13391fb33a
Create Date: 2024-08-21 23:14:44.599378

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dcc41cd48cc1"
down_revision: str | None = "df13391fb33a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "standing_tournament_id_group_id_position_key", "standing", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "standing_tournament_id_group_id_position_key",
        "standing",
        ["tournament_id", "group_id", "position"],
    )
    # ### end Alembic commands ###
