"""empty message

Revision ID: e7d5680203b8
Revises: beb33d17062a
Create Date: 2024-10-13 00:04:55.434104

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7d5680203b8"
down_revision: str | None = "beb33d17062a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tournament", "number", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tournament", "number", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
