"""empty message

Revision ID: e8f725d183e1
Revises: 77a777444a13
Create Date: 2024-08-19 00:33:02.541195

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8f725d183e1"
down_revision: str | None = "77a777444a13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "encounter", "tournament_group_id", existing_type=sa.BIGINT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "encounter", "tournament_group_id", existing_type=sa.BIGINT(), nullable=False
    )
    # ### end Alembic commands ###
