export enum LogStatsName {
  Eliminations = "eliminations",
  FinalBlows = "final_blows",
  Deaths = "deaths",
  AllDamageDealt = "all_damage_dealt",
  BarrierDamageDealt = "barrier_damage_dealt",
  HeroDamageDealt = "hero_damage_dealt",
  HealingDealt = "healing_dealt",
  HealingReceived = "healing_received",
  SelfHealing = "self_healing",
  DamageTaken = "damage_taken",
  DamageBlocked = "damage_blocked",
  DefensiveAssists = "defensive_assists",
  OffensiveAssists = "offensive_assists",
  UltimatesEarned = "ultimates_earned",
  UltimatesUsed = "ultimates_used",
  MultikillBest = "multikill_best",
  Multikills = "multikills",
  SoloKills = "solo_kills",
  ObjectiveKills = "objective_kills",
  EnvironmentalKills = "environmental_kills",
  EnvironmentalDeaths = "environmental_deaths",
  CriticalHits = "critical_hits",
  CriticalHitAccuracy = "critical_hit_accuracy",
  ScopedAccuracy = "scoped_accuracy",
  ScopedCriticalHitAccuracy = "scoped_critical_hit_accuracy",
  ScopedCriticalHitKills = "scoped_critical_hit_kills",
  ShotsFired = "shots_fired",
  ShotsHit = "shots_hit",
  ShotsMissed = "shots_missed",
  ScopedShotsFired = "scoped_shots_fired",
  ScopedShotsHit = "scoped_shots_hit",
  WeaponAccuracy = "weapon_accuracy",
  HeroTimePlayed = "hero_time_played",

  Performance = "performance",
  PerformancePoints = "performance_points",
  KD = "kd",
  KDA = "kda",
  DamageDelta = "damage_delta",
  FBE = "fbe",
  DamageFB = "damage_fb",
  Assists = "assists",

  Winrate = "winrate"
}
