"""RabbitMQ messaging configuration with dead letter queues."""

from .config import (
    BALANCER_JOBS_DLQ,
    BALANCER_JOBS_QUEUE,
    DISCORD_COMMANDS_DLQ,
    DISCORD_COMMANDS_QUEUE,
    DLX_EXCHANGE,
    PROCESS_MATCH_LOG_DLQ,
    PROCESS_MATCH_LOG_QUEUE,
    PROCESS_TOURNAMENT_LOGS_DLQ,
    PROCESS_TOURNAMENT_LOGS_QUEUE,
    TOURNAMENT_RECALC_DLQ,
    TOURNAMENT_RECALC_EXCHANGE,
    TOURNAMENT_RECALC_QUEUE,
    TOURNAMENT_RECALCULATED_DLQ,
    TOURNAMENT_RECALCULATED_QUEUE,
)

__all__ = [
    "DLX_EXCHANGE",
    "BALANCER_JOBS_QUEUE",
    "BALANCER_JOBS_DLQ",
    "DISCORD_COMMANDS_QUEUE",
    "DISCORD_COMMANDS_DLQ",
    "PROCESS_MATCH_LOG_QUEUE",
    "PROCESS_MATCH_LOG_DLQ",
    "PROCESS_TOURNAMENT_LOGS_QUEUE",
    "PROCESS_TOURNAMENT_LOGS_DLQ",
    "TOURNAMENT_RECALC_EXCHANGE",
    "TOURNAMENT_RECALC_QUEUE",
    "TOURNAMENT_RECALC_DLQ",
    "TOURNAMENT_RECALCULATED_QUEUE",
    "TOURNAMENT_RECALCULATED_DLQ",
]
