"""empty message

Revision ID: 16480ba1a731
Revises: 70cc654fb60b
Create Date: 2024-08-22 16:09:10.507093

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16480ba1a731"
down_revision: str | None = "70cc654fb60b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_match_statistics_hero_id"),
        "match_statistics",
        ["hero_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_statistics_match_id"),
        "match_statistics",
        ["match_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_statistics_user_id"),
        "match_statistics",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_match_statistics_user_id"), table_name="match_statistics")
    op.drop_index(op.f("ix_match_statistics_match_id"), table_name="match_statistics")
    op.drop_index(op.f("ix_match_statistics_hero_id"), table_name="match_statistics")
    # ### end Alembic commands ###
