"""empty message

Revision ID: 2e53410d9154
Revises: bbdb5fed5498
Create Date: 2025-01-07 18:52:14.288669

"""

from collections.abc import Sequence

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2e53410d9154"
down_revision: str | None = "13ff241c4939"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "player",
        "role",
        existing_type=postgresql.ENUM("tank", "damage", "support", name="heroclass"),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "player",
        "role",
        existing_type=postgresql.ENUM("tank", "damage", "support", name="heroclass"),
        nullable=False,
    )
    # ### end Alembic commands ###
