"""empty message

Revision ID: 333d41816f7d
Revises: 7de68d5f9982
Create Date: 2025-02-02 19:54:14.672727

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "333d41816f7d"
down_revision: str | None = "7de68d5f9982"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("analytics_player_id_fkey", "analytics", type_="foreignkey")
    op.create_foreign_key(
        None, "analytics", "player", ["player_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "analytics", type_="foreignkey")
    op.create_foreign_key(
        "analytics_player_id_fkey",
        "analytics",
        "user",
        ["player_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
