"""empty message

Revision ID: 53aedb5ec951
Revises: 16480ba1a731
Create Date: 2024-08-22 16:10:51.529888

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53aedb5ec951"
down_revision: str | None = "16480ba1a731"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_match_statistics_hero_id", table_name="match_statistics")
    op.drop_index("ix_match_statistics_user_id", table_name="match_statistics")
    op.create_index(
        op.f("ix_match_statistics_name"), "match_statistics", ["name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_match_statistics_name"), table_name="match_statistics")
    op.create_index(
        "ix_match_statistics_user_id", "match_statistics", ["user_id"], unique=False
    )
    op.create_index(
        "ix_match_statistics_hero_id", "match_statistics", ["hero_id"], unique=False
    )
    # ### end Alembic commands ###
