"""empty message

Revision ID: 6c30bf8c0a1d
Revises: 333d41816f7d
Create Date: 2025-02-02 19:57:28.265055

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c30bf8c0a1d"
down_revision: str | None = "333d41816f7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("analytics", "shift_one", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("analytics", "shift_two", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("analytics", "shift", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("analytics", "shift", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "analytics", "shift_two", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "analytics", "shift_one", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
