"""empty message

Revision ID: 8e5740828039
Revises: 532d0ac72498
Create Date: 2024-10-17 02:24:42.683021

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e5740828039"
down_revision: str | None = "532d0ac72498"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_challonge_team_id"), "challonge_team", ["id"], unique=False
    )
    op.create_index(op.f("ix_encounter_id"), "encounter", ["id"], unique=False)
    op.create_index(
        op.f("ix_encounter_tournament_id"), "encounter", ["tournament_id"], unique=False
    )
    op.create_index(op.f("ix_gamemode_id"), "gamemode", ["id"], unique=False)
    op.create_index(op.f("ix_hero_id"), "hero", ["id"], unique=False)
    op.create_index(op.f("ix_map_id"), "map", ["id"], unique=False)
    op.create_index(
        op.f("ix_match_away_team_id"), "match", ["away_team_id"], unique=False
    )
    op.create_index(
        op.f("ix_match_encounter_id"), "match", ["encounter_id"], unique=False
    )
    op.create_index(
        op.f("ix_match_home_team_id"), "match", ["home_team_id"], unique=False
    )
    op.create_index(op.f("ix_match_id"), "match", ["id"], unique=False)
    op.create_index(op.f("ix_match_map_id"), "match", ["map_id"], unique=False)
    op.create_index(
        op.f("ix_match_statistics_id"), "match_statistics", ["id"], unique=False
    )
    op.create_index(op.f("ix_player_id"), "player", ["id"], unique=False)
    op.create_index(
        op.f("ix_standing_group_id"), "standing", ["group_id"], unique=False
    )
    op.create_index(op.f("ix_standing_id"), "standing", ["id"], unique=False)
    op.create_index(op.f("ix_standing_team_id"), "standing", ["team_id"], unique=False)
    op.create_index(
        op.f("ix_standing_tournament_id"), "standing", ["tournament_id"], unique=False
    )
    op.create_index(op.f("ix_team_id"), "team", ["id"], unique=False)
    op.create_index(op.f("ix_tournament_id"), "tournament", ["id"], unique=False)
    op.create_index(
        op.f("ix_tournament_group_id"), "tournament_group", ["id"], unique=False
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_battle_tag_id"), "user_battle_tag", ["id"], unique=False
    )
    op.create_index(op.f("ix_user_discord_id"), "user_discord", ["id"], unique=False)
    op.create_index(op.f("ix_user_twitch_id"), "user_twitch", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_twitch_id"), table_name="user_twitch")
    op.drop_index(op.f("ix_user_discord_id"), table_name="user_discord")
    op.drop_index(op.f("ix_user_battle_tag_id"), table_name="user_battle_tag")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_tournament_group_id"), table_name="tournament_group")
    op.drop_index(op.f("ix_tournament_id"), table_name="tournament")
    op.drop_index(op.f("ix_team_id"), table_name="team")
    op.drop_index(op.f("ix_standing_tournament_id"), table_name="standing")
    op.drop_index(op.f("ix_standing_team_id"), table_name="standing")
    op.drop_index(op.f("ix_standing_id"), table_name="standing")
    op.drop_index(op.f("ix_standing_group_id"), table_name="standing")
    op.drop_index(op.f("ix_player_id"), table_name="player")
    op.drop_index(op.f("ix_match_statistics_id"), table_name="match_statistics")
    op.drop_index(op.f("ix_match_map_id"), table_name="match")
    op.drop_index(op.f("ix_match_id"), table_name="match")
    op.drop_index(op.f("ix_match_home_team_id"), table_name="match")
    op.drop_index(op.f("ix_match_encounter_id"), table_name="match")
    op.drop_index(op.f("ix_match_away_team_id"), table_name="match")
    op.drop_index(op.f("ix_map_id"), table_name="map")
    op.drop_index(op.f("ix_hero_id"), table_name="hero")
    op.drop_index(op.f("ix_gamemode_id"), table_name="gamemode")
    op.drop_index(op.f("ix_encounter_tournament_id"), table_name="encounter")
    op.drop_index(op.f("ix_encounter_id"), table_name="encounter")
    op.drop_index(op.f("ix_challonge_team_id"), table_name="challonge_team")
    # ### end Alembic commands ###
