"""empty message

Revision ID: 8fc92da0b204
Revises: b1969a2bc17b
Create Date: 2024-10-20 14:33:11.137838

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8fc92da0b204"
down_revision: str | None = "b1969a2bc17b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "match_assists", "hero_id", existing_type=sa.BIGINT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "match_assists", "hero_id", existing_type=sa.BIGINT(), nullable=False
    )
    # ### end Alembic commands ###
