"""empty message

Revision ID: 9fb258693e52
Revises: a39cf19146e9
Create Date: 2025-01-17 20:10:59.022249

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fb258693e52"
down_revision: str | None = "a39cf19146e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_match_statistics_value", table_name="match_statistics")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_match_statistics_value", "match_statistics", ["value"], unique=False
    )
    # ### end Alembic commands ###
