"""empty message

Revision ID: a82dd80b2fb7
Revises: e8f725d183e1
Create Date: 2024-08-19 17:52:48.905467

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a82dd80b2fb7"
down_revision: str | None = "e8f725d183e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player",
        sa.Column(
            "is_substitution", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column("player", sa.Column("related_player_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player", "related_player_id")
    op.drop_column("player", "is_substitution")
    # ### end Alembic commands ###
