"""empty message

Revision ID: b1969a2bc17b
Revises: 60be498bbf6c
Create Date: 2024-10-20 14:13:58.948719

"""

from collections.abc import Sequence

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b1969a2bc17b"
down_revision: str | None = "60be498bbf6c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "match_kill_feed",
        "ability",
        existing_type=postgresql.ENUM(
            "PrimaryFire",
            "SecondaryFire",
            "Ability1",
            "Ability2",
            "Ultimate",
            "Melee",
            name="abilityevent",
        ),
        nullable=True,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "match_kill_feed",
        "ability",
        existing_type=postgresql.ENUM(
            "PrimaryFire",
            "SecondaryFire",
            "Ability1",
            "Ability2",
            "Ultimate",
            "Melee",
            name="abilityevent",
        ),
        nullable=False,
    )
    # ### end Alembic commands ###
