"""empty message

Revision ID: bcf1791bf58a
Revises: d8864b6e7fa2
Create Date: 2024-08-21 18:27:11.964244

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcf1791bf58a"
down_revision: str | None = "d8864b6e7fa2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player", sa.Column("div", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player", "div")
    # ### end Alembic commands ###
