"""empty message

Revision ID: c923a847f869
Revises: bcf1791bf58a
Create Date: 2024-08-21 18:48:47.839052

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c923a847f869"
down_revision: str | None = "bcf1791bf58a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("player", "div", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("player", "div", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
