"""empty message

Revision ID: d8864b6e7fa2
Revises: 57ce862080c0
Create Date: 2024-08-20 19:32:32.935725

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8864b6e7fa2"
down_revision: str | None = "57ce862080c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_player_tournament_id"), "player", ["tournament_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_player_tournament_id"), table_name="player")
    # ### end Alembic commands ###
