"""empty message

Revision ID: df13391fb33a
Revises: 1cdb89deeacd
Create Date: 2024-08-21 23:13:37.619818

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df13391fb33a"
down_revision: str | None = "1cdb89deeacd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        None, "standing", ["tournament_id", "group_id", "position"]
    )
    op.create_unique_constraint(
        None, "standing", ["tournament_id", "group_id", "team_id"]
    )
    op.create_unique_constraint(None, "standing", ["tournament_id", "group_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "standing", type_="unique")
    op.drop_constraint(None, "standing", type_="unique")
    op.drop_constraint(None, "standing", type_="unique")
    # ### end Alembic commands ###
