"""empty message

Revision ID: e4015fc886cc
Revises: 9a49a3beab5b
Create Date: 2024-10-12 15:43:13.054539

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4015fc886cc"
down_revision: str | None = "9a49a3beab5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match", sa.Column("log_name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "log_name")
    # ### end Alembic commands ###
