"""empty message

Revision ID: f66ec131d22f
Revises: f4a321d08a52
Create Date: 2024-08-20 14:27:27.702103

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f66ec131d22f"
down_revision: str | None = "f4a321d08a52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_encounter_away_team_id"), "encounter", ["away_team_id"], unique=False
    )
    op.create_index(
        op.f("ix_encounter_home_team_id"), "encounter", ["home_team_id"], unique=False
    )
    op.create_index(op.f("ix_encounter_round"), "encounter", ["round"], unique=False)
    op.create_index(op.f("ix_team_captain_id"), "team", ["captain_id"], unique=False)
    op.create_index(
        op.f("ix_team_tournament_id"), "team", ["tournament_id"], unique=False
    )
    op.drop_constraint(
        "user_battle_tag_battle_tag_key", "user_battle_tag", type_="unique"
    )
    op.create_index(
        op.f("ix_user_battle_tag_battle_tag"),
        "user_battle_tag",
        ["battle_tag"],
        unique=True,
    )
    op.create_index(
        op.f("ix_user_battle_tag_name"), "user_battle_tag", ["name"], unique=False
    )
    op.drop_constraint("user_discord_name_key", "user_discord", type_="unique")
    op.create_index(op.f("ix_user_discord_name"), "user_discord", ["name"], unique=True)
    op.drop_constraint("user_twitch_name_key", "user_twitch", type_="unique")
    op.create_index(op.f("ix_user_twitch_name"), "user_twitch", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_twitch_name"), table_name="user_twitch")
    op.create_unique_constraint("user_twitch_name_key", "user_twitch", ["name"])
    op.drop_index(op.f("ix_user_discord_name"), table_name="user_discord")
    op.create_unique_constraint("user_discord_name_key", "user_discord", ["name"])
    op.drop_index(op.f("ix_user_battle_tag_name"), table_name="user_battle_tag")
    op.drop_index(op.f("ix_user_battle_tag_battle_tag"), table_name="user_battle_tag")
    op.create_unique_constraint(
        "user_battle_tag_battle_tag_key", "user_battle_tag", ["battle_tag"]
    )
    op.drop_index(op.f("ix_team_tournament_id"), table_name="team")
    op.drop_index(op.f("ix_team_captain_id"), table_name="team")
    op.drop_index(op.f("ix_encounter_round"), table_name="encounter")
    op.drop_index(op.f("ix_encounter_home_team_id"), table_name="encounter")
    op.drop_index(op.f("ix_encounter_away_team_id"), table_name="encounter")
    # ### end Alembic commands ###
