"""empty message

Revision ID: f7fe195a753d
Revises: ee92688775b8
Create Date: 2024-08-18 23:00:20.085677

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7fe195a753d"
down_revision: str | None = "ee92688775b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "challonge_team", sa.Column("tournament_id", sa.BigInteger(), nullable=False)
    )
    op.alter_column(
        "challonge_team", "group_id", existing_type=sa.BIGINT(), nullable=True
    )
    op.create_foreign_key(
        None,
        "challonge_team",
        "tournament",
        ["tournament_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "challonge_team", type_="foreignkey")
    op.alter_column(
        "challonge_team", "group_id", existing_type=sa.BIGINT(), nullable=False
    )
    op.drop_column("challonge_team", "tournament_id")
    # ### end Alembic commands ###
